import type { User, Complaint, Appointment, DocumentRequest, Bill } from './types';

export const mockUser: User = {
  id: 'user123',
  name: 'Aarav Sharma',
  phone: '9876543210',
  location: 'Bengaluru',
  aadhaarId: 'XXXX-XXXX-1234',
  pan: 'ABCDE1234F',
};

export const mockComplaints: Complaint[] = [
  {
    id: 'COMP123',
    userId: 'user123',
    type: 'Public',
    category: 'Civic & Municipal',
    subcategory: 'Potholes',
    description: 'Large pothole on MG Road near the metro station is causing traffic issues.',
    location: 'MG Road, Bengaluru',
    coords: { lat: 12.9756, lng: 77.6069 },
    status: 'In Progress',
    upvotes: 25,
    response: 'Under review by BBMP. A team has been assigned.',
    createdAt: '2024-07-20T10:00:00Z',
  },
  {
    id: 'COMP124',
    userId: 'user123',
    type: 'Private',
    category: 'Utility Services',
    subcategory: 'Incorrect Electricity Bill',
    description: 'My electricity bill for this month is unusually high. Please review.',
    location: 'Koramangala, Bengaluru',
    coords: { lat: 12.9352, lng: 77.6245 },
    status: 'Resolved',
    upvotes: 0,
    response: 'Billing error corrected. Revised bill has been issued.',
    createdAt: '2024-07-18T14:30:00Z',
  },
  {
    id: 'COMP125',
    userId: 'user456',
    type: 'Public',
    category: 'Civic & Municipal',
    subcategory: 'Garbage not collected',
    description: 'Garbage has not been collected in our area for the past 3 days. It is causing a health hazard.',
    location: 'Indiranagar, Bengaluru',
    coords: { lat: 12.9784, lng: 77.6408 },
    status: 'Pending',
    upvotes: 12,
    createdAt: '2024-07-21T09:00:00Z',
  },
  {
    id: 'COMP126',
    userId: 'user789',
    type: 'Public',
    category: 'Transport',
    subcategory: 'Broken Streetlight',
    description: 'Streetlight on 100ft Road is not working.',
    location: 'Indiranagar, Bengaluru',
    coords: { lat: 12.9718, lng: 77.6385 },
    status: 'Resolved',
    upvotes: 8,
    response: 'BESCOM has replaced the faulty streetlight.',
    createdAt: '2024-07-15T20:00:00Z',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'APPT456',
    userId: 'user123',
    category: 'Identity & Certificates',
    subcategory: 'Aadhaar Update',
    date: new Date('2024-08-05T00:00:00Z'),
    time: '11:00 AM',
    location: 'Aadhaar Seva Kendra, Jayanagar',
    status: 'Upcoming',
  },
  {
    id: 'APPT457',
    userId: 'user123',
    category: 'Transport',
    subcategory: "Driver's License Renewal",
    date: new Date('2024-07-10T00:00:00Z'),
    time: '02:30 PM',
    location: 'RTO, Koramangala',
    status: 'Completed',
  },
];

export const mockDocumentRequests: DocumentRequest[] = [
  {
    id: 'DOC789',
    userId: 'user123',
    category: 'Identity Documents',
    subcategory: 'Birth Certificate',
    status: 'Resolved',
    createdAt: '2024-07-12T11:00:00Z',
    fileUrl: '/mock-birth-certificate.pdf',
  },
  {
    id: 'DOC790',
    userId: 'user123',
    category: 'Property Documents',
    subcategory: 'Property Tax Receipt',
    status: 'Pending',
    createdAt: '2024-07-22T16:00:00Z',
  },
];

export const mockBills: Bill[] = [
  {
    id: 'BILL789',
    userId: 'user123',
    consumerId: 'E12345678',
    utility: 'Electricity - BESCOM',
    amount: 1250.75,
    dueDate: '2024-08-10',
    status: 'Pending',
    serviceArea: 'Koramangala',
  },
  {
    id: 'BILL790',
    userId: 'user123',
    consumerId: 'W87654321',
    utility: 'Water - BWSSB',
    amount: 450.0,
    dueDate: '2024-08-15',
    status: 'Pending',
    serviceArea: 'Koramangala',
  },
  {
    id: 'BILL791',
    userId: 'user123',
    consumerId: 'P99887766',
    utility: 'Property Tax - BBMP',
    amount: 5500.0,
    dueDate: '2024-07-30',
    status: 'Paid',
    serviceArea: 'Koramangala',
  },
];
